// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	pandora "github.com/nlowe/mousiki/pandora"
	mock "github.com/stretchr/testify/mock"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// GetMoreTracks provides a mock function with given fields: stationId
func (_m *Client) GetMoreTracks(stationId string) ([]pandora.Track, error) {
	ret := _m.Called(stationId)

	var r0 []pandora.Track
	if rf, ok := ret.Get(0).(func(string) []pandora.Track); ok {
		r0 = rf(stationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pandora.Track)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(stationId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStations provides a mock function with given fields:
func (_m *Client) GetStations() ([]pandora.Station, error) {
	ret := _m.Called()

	var r0 []pandora.Station
	if rf, ok := ret.Get(0).(func() []pandora.Station); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pandora.Station)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Login provides a mock function with given fields: username, password
func (_m *Client) Login(username string, password string) error {
	ret := _m.Called(username, password)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(username, password)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
